export const actionType = {
    SIGNUP_USER: 'SIGNUP_USER',
    LOGIN_USER_DATA: 'LOGIN_USER_DATA',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_ADD_PRODUCT: 'REMOVE_ADD_PRODUCT',
    SELECT_PRODUCT_REMOVE: 'SELECT_PRODUCT_REMOVE',
    BUY_NOW_PRODUCT: 'BUY_NOW_PRODUCT'
}